output "backup_bucket_name" {
  description = "The name of the backup bucket generated by the module to store all the .tsbak files."
  value       = module.tableau_backup_config.backup_bucket_id
}

output "lambda_artefact_bucket_id" {
  value = module.tableau_lambda_artefacts.lambda_artefact_bucket_id
}
